spring.application.name=envases-inventory
# Database Configuration

spring.datasource.driver-class-name=org.mariadb.jdbc.Driver
spring.datasource.url=jdbc:mariadb://localhost:3306/todoenvases
spring.datasource.username=bdserver
spring.datasource.password=asl121mde3v-@

# PRUEBAS LOCALES
#spring.datasource.url=jdbc:mariadb://localhost:3306/envases_inventory2
#spring.datasource.username=root
#spring.datasource.password=root
spring.jpa.hibernate.ddl-auto=update

# HikariCP Configuration
# (la base de datos esta sufriendo al importar muchos datos, asi que aumentamos algunos tiempos)
spring.datasource.hikari.max-lifetime=300000
spring.datasource.hikari.idle-timeout=240000
spring.datasource.hikari.validation-timeout=5000
spring.datasource.hikari.connection-timeout=30000
spring.datasource.hikari.keepalive-time=30000
spring.datasource.hikari.maximum-pool-size=10
spring.datasource.hikari.minimum-idle=2
spring.jpa.properties.hibernate.jdbc.batch_size=50
spring.jpa.properties.hibernate.order_inserts=true
spring.jpa.properties.hibernate.order_updates=true
spring.jpa.properties.hibernate.jdbc.batch_versioned_data=true




# JPA Configuration
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.hibernate.naming.physical-strategy=org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl

# JWT Configuration
jwt.secret=mySuperSecretKeyThatIsAtLeast32Chars!
jwt.expiration=86400000

# Server Configuration
# swagger-ui custom path
springdoc.swagger-ui.path=/swagger-ui.html
# /api-docs endpoint custom path
springdoc.api-docs.path=/api-

# Logging
#logging.level.com.sipcommb.envases=DEBUG
#logging.level.org.springframework.security=DEBUG
logging.file.name=/usr/local/tomcat/tomcat8/logs/spring-app.log
logging.level.root=INFO