spring.application.name=envases-inventory
# Database Configuration
spring.datasource.driver-class-name=org.mariadb.jdbc.Driver
spring.datasource.url=jdbc:mariadb://localhost:3306/todoenvases
spring.datasource.username=bdserver
spring.datasource.password=asl121mde3v-@
spring.jpa.hibernate.ddl-auto=update

# JPA Configuration
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.hibernate.naming.physical-strategy=org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl

# JWT Configuration
jwt.secret=mySuperSecretKeyThatIsAtLeast32Chars!
jwt.expiration=86400000

# Server Configuration
# swagger-ui custom path
springdoc.swagger-ui.path=/swagger-ui.html
# /api-docs endpoint custom path
springdoc.api-docs.path=/api-

# Logging
#logging.level.com.sipcommb.envases=DEBUG
#logging.level.org.springframework.security=DEBUG