version: '3.8'

services:
  mariadb:
    image: mariadb:latest
    container_name: mariadb_envases
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: todoenvases
      MYSQL_USER: bdserver
      MYSQL_PASSWORD: asl121mde3v-@
    ports:
      - "3306:3306"
    volumes:
      - mariadb_data:/var/lib/mysql
    restart: always

volumes:
  mariadb_data: