FROM mariadb:latest

# Set environment variables for MariaDB
ENV MYSQL_ROOT_PASSWORD=root
ENV MYSQL_DATABASE=envases_inventory
ENV MYSQL_USER=test_user
ENV MYSQL_PASSWORD=pass

# Expose MariaDB port
EXPOSE 3306